# Generated by Django 5.1.2 on 2024-10-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='clear_by_receiver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='clear_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
